HelpError: HelpError now takes arguments rathern than a dict.
Previously HelpError was passed a dict to determine what would be shown
in the help message.  This was tedious and has been replaced with a
regular set of arguments in the constructor.

Signed-off-by: Govind Salinas blix@sophiasuchtig.com